### ISSUE TITLE
Message not sent but console shows message sent 

### ISSUE THREAD

**Issue by nitinkumar30** [mekaokeke/automated-whatsapp-birthday-reminders#1]
My code shows message sent but in whatsapp, it's not sent !

Used below code:

```
birthdays = {
    # "John" : date(2000, 1, 13),
    'Nitin' : date(1999, 3, 19),
    'Somi' : date(1995, 6, 14)
}
```

& given 2 diff nos in `numbers{}`

But, the reminder is not sent via the whatsapp web, which is already logged in ! What could be the possible reason? Is this still running correctly in your system?

**Comment by mekaokeke** [comment]
Yes it is but the reminders are set to be sent the day before. So since
Nitin birthday is on the 19 the reminders will be sent tomorrow. You if you
want reminders to be sent two days in advance you need to set the time
delta to 2 instead of 1.

**Comment by nitinkumar30** [comment]
Is there any time constraint after which message will not be typed? Let's say I'm running script at 9PM on 21st March, but birthday is on 22nd March. Will it still message in that time?

**Comment by mekaokeke** [comment]
Yes it will. It sends it as soon as it runs. But if you leave it running it
will run every day around 9pm. So all your messages will be sent around 9pm

**Comment by nitinkumar30** [comment]
It's actually not sending any messages. How much do we need to wait?

What I'm actually doing is just running & it's automatically opening web.whatsapp.com in my browser & selecting the contact, but not messaging that contact. Even textbox of whatsapp chat is also not active.

**Comment by mekaokeke** [comment]
Did you add a message to be sent? And if you have is the textbox being
populated with that message? Cause it works fine for me

**Comment by nitinkumar30** [comment]
Yes, below is the code I'm using for that:

```
   for person in birthdays.keys():
        if month == birthdays[person].month and day == birthdays[person].day:
            print("{} is having birthday. Wish him birthday !".format(person))
            celebrants.append(person)
```

**Comment by mekaokeke** [comment]
That’s not where the messages are being formed. That print statement just
goes to your terminal to let you know that it found a birthday and whose
birthday it is. If you look further down you’ll see a line of code that
says message=“”. In the quotes that’s where you put your message

**Comment by nitinkumar30** [comment]
Can you quickly share the line no in your code for further analysis. Also, if you can go through my code & let me know exactly where I'm missing.

**Comment by mekaokeke** [comment]
Yeah show me what you have and I’ll tell you what to do
